// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/linkflow-ai/linkflow/internal/adapters/messaging/asynq"
	"github.com/linkflow-ai/linkflow/internal/adapters/persistence/postgres"
	"github.com/linkflow-ai/linkflow/internal/adapters/persistence/postgres/repositories"
	"github.com/linkflow-ai/linkflow/internal/adapters/persistence/redis"
	"github.com/linkflow-ai/linkflow/internal/core/domain/schedule"
	"github.com/linkflow-ai/linkflow/internal/core/domain/workflow"
	"github.com/linkflow-ai/linkflow/internal/infrastructure/config"
	"github.com/linkflow-ai/linkflow/internal/infrastructure/observability/logger"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeSchedulerApp wires all dependencies
func InitializeSchedulerApp() (*SchedulerApp, error) {
	config, err := provideSchedulerConfig()
	if err != nil {
		return nil, err
	}
	logger := provideSchedulerLogger(config)
	db, err := provideSchedulerGormDB(config)
	if err != nil {
		return nil, err
	}
	client := provideSchedulerPostgresClient(db)
	redisClient, err := provideSchedulerRedis(config)
	if err != nil {
		return nil, err
	}
	asynqClient, err := provideSchedulerAsynqClient(config)
	if err != nil {
		return nil, err
	}
	scheduleRepository := repositories.NewScheduleRepository(db)
	workflowRepository := repositories.NewWorkflowRepository(db)
	schedulerApp := provideSchedulerApp(config, logger, client, redisClient, asynqClient, scheduleRepository, workflowRepository)
	return schedulerApp, nil
}

// wire.go:

// SchedulerApp holds all dependencies for the scheduler service
type SchedulerApp struct {
	Config *config.Config
	Logger logger.Logger
	DB     *postgres.Client
	Redis  *redis.Client
	Queue  *asynq.Client

	// Repositories
	ScheduleRepo schedule.Repository
	WorkflowRepo workflow.Repository
}

// Infrastructure provider set
var schedulerInfraSet = wire.NewSet(
	provideSchedulerConfig,
	provideSchedulerLogger,
	provideSchedulerGormDB,
	provideSchedulerPostgresClient,
	provideSchedulerRedis,
	provideSchedulerAsynqClient,
)

// Repository provider set
var schedulerRepoSet = wire.NewSet(repositories.NewScheduleRepository, repositories.NewWorkflowRepository, wire.Bind(new(schedule.Repository), new(*repositories.ScheduleRepository)), wire.Bind(new(workflow.Repository), new(*repositories.WorkflowRepository)))

func provideSchedulerConfig() (*config.Config, error) {
	configPath := "configs/config.yaml"
	return config.Load(configPath)
}

func provideSchedulerLogger(cfg *config.Config) logger.Logger {
	if cfg.App.IsDevelopment() {
		return logger.NewDevelopment()
	}
	return logger.NewDefault()
}

func provideSchedulerGormDB(cfg *config.Config) (*gorm.DB, error) {
	return postgres.NewClient(postgres.Config{
		Host:         cfg.Database.Host,
		Port:         cfg.Database.Port,
		User:         cfg.Database.User,
		Password:     cfg.Database.Password,
		Database:     cfg.Database.Name,
		SSLMode:      cfg.Database.SSLMode,
		MaxOpenConns: cfg.Database.MaxOpenConns,
		MaxIdleConns: cfg.Database.MaxIdleConns,
		MaxLifetime:  cfg.Database.MaxLifetime,
	})
}

func provideSchedulerPostgresClient(db *gorm.DB) *postgres.Client {
	return postgres.NewClientWrapper(db)
}

func provideSchedulerRedis(cfg *config.Config) (*redis.Client, error) {
	return redis.NewClient(redis.Config{
		Host:     cfg.Redis.Host,
		Port:     cfg.Redis.Port,
		Password: cfg.Redis.Password,
		DB:       cfg.Redis.DB,
		PoolSize: cfg.Redis.PoolSize,
	})
}

func provideSchedulerAsynqClient(cfg *config.Config) (*asynq.Client, error) {
	return asynq.NewClient(asynq.Config{
		RedisAddr:     cfg.Redis.GetAddress(),
		RedisPassword: cfg.Redis.Password,
		RedisDB:       cfg.Redis.DB,
	})
}

func provideSchedulerApp(
	cfg *config.Config,
	log logger.Logger,
	db *postgres.Client, redis2 *redis.Client,
	queue *asynq.Client,
	scheduleRepo schedule.Repository,
	workflowRepo workflow.Repository,
) *SchedulerApp {
	return &SchedulerApp{
		Config:       cfg,
		Logger:       log,
		DB:           db,
		Redis:        redis2,
		Queue:        queue,
		ScheduleRepo: scheduleRepo,
		WorkflowRepo: workflowRepo,
	}
}
