// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/linkflow-ai/linkflow/internal/pkg/config"
	"github.com/linkflow-ai/linkflow/internal/pkg/queue"
	"github.com/linkflow-ai/linkflow/internal/pkg/redis"
	"github.com/linkflow-ai/linkflow/internal/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeSchedulerApp wires all dependencies and returns the SchedulerApp
func InitializeSchedulerApp() (*SchedulerApp, error) {
	config, err := wire.ProvideConfig()
	if err != nil {
		return nil, err
	}
	db, err := wire.ProvideDB(config)
	if err != nil {
		return nil, err
	}
	client, err := wire.ProvideRedis(config)
	if err != nil {
		return nil, err
	}
	queueClient := wire.ProvideQueue(config)
	schedulerApp := provideSchedulerApp(config, db, client, queueClient)
	return schedulerApp, nil
}

// wire.go:

// SchedulerApp holds all initialized dependencies for scheduler
type SchedulerApp struct {
	Config *config.Config
	DB     *gorm.DB
	Redis  *redis.Client
	Queue  *queue.Client
}

// provideSchedulerApp creates the SchedulerApp struct with all dependencies
func provideSchedulerApp(
	cfg *config.Config,
	db *gorm.DB, redis2 *redis.Client, queue2 *queue.Client,
) *SchedulerApp {
	return &SchedulerApp{
		Config: cfg,
		DB:     db,
		Redis:  redis2,
		Queue:  queue2,
	}
}
