// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/linkflow-ai/linkflow/internal/domain/repositories"
	"github.com/linkflow-ai/linkflow/internal/domain/services"
	"github.com/linkflow-ai/linkflow/internal/pkg/config"
	"github.com/linkflow-ai/linkflow/internal/pkg/crypto"
	"github.com/linkflow-ai/linkflow/internal/pkg/queue"
	"github.com/linkflow-ai/linkflow/internal/pkg/redis"
	"github.com/linkflow-ai/linkflow/internal/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeWorkerApp wires all dependencies and returns the WorkerApp
func InitializeWorkerApp() (*WorkerApp, error) {
	config, err := wire.ProvideConfig()
	if err != nil {
		return nil, err
	}
	db, err := wire.ProvideDB(config)
	if err != nil {
		return nil, err
	}
	client, err := wire.ProvideRedis(config)
	if err != nil {
		return nil, err
	}
	queueClient := wire.ProvideQueue(config)
	encryptor, err := wire.ProvideEncryptor(config)
	if err != nil {
		return nil, err
	}
	workflowRepository := repositories.NewWorkflowRepository(db)
	workflowVersionRepository := repositories.NewWorkflowVersionRepository(db)
	webhookEndpointRepository := repositories.NewWebhookEndpointRepository(db)
	workflowService := wire.ProvideWorkflowService(workflowRepository, workflowVersionRepository, webhookEndpointRepository)
	executionRepository := repositories.NewExecutionRepository(db)
	nodeExecutionRepository := repositories.NewNodeExecutionRepository(db)
	executionService := services.NewExecutionService(executionRepository, nodeExecutionRepository, workflowRepository)
	credentialRepository := repositories.NewCredentialRepository(db)
	credentialShareRepository := repositories.NewCredentialShareRepository(db)
	credentialService := services.NewCredentialService(credentialRepository, credentialShareRepository, encryptor)
	planRepository := repositories.NewPlanRepository(db)
	subscriptionRepository := repositories.NewSubscriptionRepository(db)
	usageRepository := repositories.NewUsageRepository(db)
	invoiceRepository := repositories.NewInvoiceRepository(db)
	workspaceRepository := repositories.NewWorkspaceRepository(db)
	billingService := wire.ProvideWorkerBillingService(planRepository, subscriptionRepository, usageRepository, invoiceRepository, workspaceRepository)
	oAuthStateRepository := repositories.NewOAuthStateRepository(db)
	baseURL := wire.ProvideBaseURL(config)
	frontendURL := wire.ProvideFrontendURL(config)
	oAuthService := wire.ProvideOAuthService(oAuthStateRepository, credentialRepository, encryptor, config, baseURL, frontendURL)
	workerApp := provideWorkerApp(config, db, client, queueClient, encryptor, workflowService, executionService, credentialService, billingService, oAuthService)
	return workerApp, nil
}

// wire.go:

// WorkerApp holds all initialized dependencies for worker
type WorkerApp struct {
	Config        *config.Config
	DB            *gorm.DB
	Redis         *redis.Client
	Queue         *queue.Client
	Encryptor     *crypto.Encryptor
	WorkflowSvc   *services.WorkflowService
	ExecutionSvc  *services.ExecutionService
	CredentialSvc *services.CredentialService
	BillingSvc    *services.BillingService
	OAuthSvc      *services.OAuthService
}

// provideWorkerApp creates the WorkerApp struct with all dependencies
func provideWorkerApp(
	cfg *config.Config,
	db *gorm.DB, redis2 *redis.Client, queue2 *queue.Client,
	encryptor *crypto.Encryptor,
	workflowSvc *services.WorkflowService,
	executionSvc *services.ExecutionService,
	credentialSvc *services.CredentialService,
	billingSvc *services.BillingService,
	oauthSvc *services.OAuthService,
) *WorkerApp {
	return &WorkerApp{
		Config:        cfg,
		DB:            db,
		Redis:         redis2,
		Queue:         queue2,
		Encryptor:     encryptor,
		WorkflowSvc:   workflowSvc,
		ExecutionSvc:  executionSvc,
		CredentialSvc: credentialSvc,
		BillingSvc:    billingSvc,
		OAuthSvc:      oauthSvc,
	}
}
