// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/linkflow-ai/linkflow/internal/adapters/messaging/asynq"
	"github.com/linkflow-ai/linkflow/internal/adapters/persistence/postgres"
	"github.com/linkflow-ai/linkflow/internal/adapters/persistence/postgres/repositories"
	"github.com/linkflow-ai/linkflow/internal/adapters/persistence/redis"
	"github.com/linkflow-ai/linkflow/internal/core/application/command/execution"
	"github.com/linkflow-ai/linkflow/internal/core/domain/credential"
	execution2 "github.com/linkflow-ai/linkflow/internal/core/domain/execution"
	"github.com/linkflow-ai/linkflow/internal/core/domain/schedule"
	"github.com/linkflow-ai/linkflow/internal/core/domain/workflow"
	"github.com/linkflow-ai/linkflow/internal/infrastructure/config"
	"github.com/linkflow-ai/linkflow/internal/infrastructure/crypto"
	"github.com/linkflow-ai/linkflow/internal/infrastructure/observability/logger"
	"github.com/linkflow-ai/linkflow/internal/shared/events"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeWorkerApp wires all dependencies
func InitializeWorkerApp() (*WorkerApp, error) {
	config, err := provideWorkerConfig()
	if err != nil {
		return nil, err
	}
	logger := provideWorkerLogger(config)
	db, err := provideWorkerGormDB(config)
	if err != nil {
		return nil, err
	}
	client := provideWorkerPostgresClient(db)
	redisClient, err := provideWorkerRedis(config)
	if err != nil {
		return nil, err
	}
	asynqClient, err := provideWorkerAsynqClient(config)
	if err != nil {
		return nil, err
	}
	encryptor, err := provideWorkerEncryptor(config)
	if err != nil {
		return nil, err
	}
	workflowRepository := repositories.NewWorkflowRepository(db)
	executionRepository := repositories.NewExecutionRepository(db)
	nodeExecutionRepository := repositories.NewNodeExecutionRepository(db)
	credentialRepository := repositories.NewCredentialRepository(db)
	scheduleRepository := repositories.NewScheduleRepository(db)
	bus := provideWorkerEventBus()
	startExecutionHandler := execution.NewStartExecutionHandler(workflowRepository, executionRepository, bus)
	workerApp := provideWorkerApp(config, logger, client, redisClient, asynqClient, encryptor, workflowRepository, executionRepository, nodeExecutionRepository, credentialRepository, scheduleRepository, startExecutionHandler)
	return workerApp, nil
}

// wire.go:

// WorkerApp holds all dependencies for the worker service
type WorkerApp struct {
	Config    *config.Config
	Logger    logger.Logger
	DB        *postgres.Client
	Redis     *redis.Client
	Queue     *asynq.Client
	Encryptor *crypto.Encryptor

	// Repositories
	WorkflowRepo      workflow.Repository
	ExecutionRepo     execution2.Repository
	NodeExecutionRepo execution2.NodeExecutionRepository
	CredentialRepo    credential.Repository
	ScheduleRepo      schedule.Repository

	// Command Handlers
	StartExecutionHandler *execution.StartExecutionHandler
}

// Infrastructure provider set
var workerInfraSet = wire.NewSet(
	provideWorkerConfig,
	provideWorkerLogger,
	provideWorkerGormDB,
	provideWorkerPostgresClient,
	provideWorkerRedis,
	provideWorkerAsynqClient,
	provideWorkerEncryptor,
	provideWorkerEventBus,
)

// Repository provider set
var workerRepoSet = wire.NewSet(repositories.NewWorkflowRepository, repositories.NewExecutionRepository, repositories.NewNodeExecutionRepository, repositories.NewCredentialRepository, repositories.NewScheduleRepository, wire.Bind(new(workflow.Repository), new(*repositories.WorkflowRepository)), wire.Bind(new(execution2.Repository), new(*repositories.ExecutionRepository)), wire.Bind(new(execution2.NodeExecutionRepository), new(*repositories.NodeExecutionRepository)), wire.Bind(new(credential.Repository), new(*repositories.CredentialRepository)), wire.Bind(new(schedule.Repository), new(*repositories.ScheduleRepository)))

// Command handler provider set
var workerCommandSet = wire.NewSet(execution.NewStartExecutionHandler)

func provideWorkerConfig() (*config.Config, error) {
	configPath := "configs/config.yaml"
	return config.Load(configPath)
}

func provideWorkerLogger(cfg *config.Config) logger.Logger {
	if cfg.App.IsDevelopment() {
		return logger.NewDevelopment()
	}
	return logger.NewDefault()
}

func provideWorkerGormDB(cfg *config.Config) (*gorm.DB, error) {
	return postgres.NewClient(postgres.Config{
		Host:         cfg.Database.Host,
		Port:         cfg.Database.Port,
		User:         cfg.Database.User,
		Password:     cfg.Database.Password,
		Database:     cfg.Database.Name,
		SSLMode:      cfg.Database.SSLMode,
		MaxOpenConns: cfg.Database.MaxOpenConns,
		MaxIdleConns: cfg.Database.MaxIdleConns,
		MaxLifetime:  cfg.Database.MaxLifetime,
	})
}

func provideWorkerPostgresClient(db *gorm.DB) *postgres.Client {
	return postgres.NewClientWrapper(db)
}

func provideWorkerRedis(cfg *config.Config) (*redis.Client, error) {
	return redis.NewClient(redis.Config{
		Host:     cfg.Redis.Host,
		Port:     cfg.Redis.Port,
		Password: cfg.Redis.Password,
		DB:       cfg.Redis.DB,
		PoolSize: cfg.Redis.PoolSize,
	})
}

func provideWorkerAsynqClient(cfg *config.Config) (*asynq.Client, error) {
	return asynq.NewClient(asynq.Config{
		RedisAddr:     cfg.Redis.GetAddress(),
		RedisPassword: cfg.Redis.Password,
		RedisDB:       cfg.Redis.DB,
	})
}

func provideWorkerEncryptor(cfg *config.Config) (*crypto.Encryptor, error) {
	return crypto.NewEncryptor(cfg.App.SecretKey)
}

func provideWorkerEventBus() events.Bus {
	return events.NewInMemoryBus()
}

func provideWorkerApp(
	cfg *config.Config,
	log logger.Logger,
	db *postgres.Client, redis2 *redis.Client,
	queue *asynq.Client,
	encryptor *crypto.Encryptor,
	workflowRepo workflow.Repository,
	executionRepo execution2.Repository,
	nodeExecRepo execution2.NodeExecutionRepository,
	credentialRepo credential.Repository,
	scheduleRepo schedule.Repository,
	startExecutionHandler *execution.StartExecutionHandler,
) *WorkerApp {
	return &WorkerApp{
		Config:                cfg,
		Logger:                log,
		DB:                    db,
		Redis:                 redis2,
		Queue:                 queue,
		Encryptor:             encryptor,
		WorkflowRepo:          workflowRepo,
		ExecutionRepo:         executionRepo,
		NodeExecutionRepo:     nodeExecRepo,
		CredentialRepo:        credentialRepo,
		ScheduleRepo:          scheduleRepo,
		StartExecutionHandler: startExecutionHandler,
	}
}
