// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/linkflow-ai/linkflow/internal/api"
	"github.com/linkflow-ai/linkflow/internal/domain/repositories"
	"github.com/linkflow-ai/linkflow/internal/domain/services"
	"github.com/linkflow-ai/linkflow/internal/pkg/config"
	"github.com/linkflow-ai/linkflow/internal/pkg/crypto"
	"github.com/linkflow-ai/linkflow/internal/pkg/oauth"
	"github.com/linkflow-ai/linkflow/internal/pkg/queue"
	"github.com/linkflow-ai/linkflow/internal/pkg/redis"
	"github.com/linkflow-ai/linkflow/internal/wire"
	"gorm.io/gorm"
)

import (
	_ "github.com/linkflow-ai/linkflow/internal/worker/nodes/actions"
	_ "github.com/linkflow-ai/linkflow/internal/worker/nodes/integrations"
	_ "github.com/linkflow-ai/linkflow/internal/worker/nodes/logic"
	_ "github.com/linkflow-ai/linkflow/internal/worker/nodes/triggers"
)

// Injectors from wire.go:

// InitializeApp wires all dependencies and returns the App
func InitializeApp() (*App, error) {
	config, err := wire.ProvideConfig()
	if err != nil {
		return nil, err
	}
	db, err := wire.ProvideDB(config)
	if err != nil {
		return nil, err
	}
	client, err := wire.ProvideRedis(config)
	if err != nil {
		return nil, err
	}
	queueClient := wire.ProvideQueue(config)
	jwtManager := wire.ProvideJWTManager(config)
	encryptor, err := wire.ProvideEncryptor(config)
	if err != nil {
		return nil, err
	}
	manager := wire.ProvideOAuthManager(config, db, encryptor)
	userRepository := repositories.NewUserRepository(db)
	sessionRepository := repositories.NewSessionRepository(db)
	otpManager := wire.ProvideOTPManager(config)
	authService := services.NewAuthService(userRepository, sessionRepository, jwtManager, otpManager, encryptor)
	userService := services.NewUserService(userRepository)
	workspaceRepository := repositories.NewWorkspaceRepository(db)
	workspaceMemberRepository := repositories.NewWorkspaceMemberRepository(db)
	workspaceInvitationRepository := repositories.NewWorkspaceInvitationRepository(db)
	workspaceService := services.NewWorkspaceService(workspaceRepository, workspaceMemberRepository, workspaceInvitationRepository)
	workflowRepository := repositories.NewWorkflowRepository(db)
	workflowVersionRepository := repositories.NewWorkflowVersionRepository(db)
	webhookEndpointRepository := repositories.NewWebhookEndpointRepository(db)
	workflowService := wire.ProvideWorkflowService(workflowRepository, workflowVersionRepository, webhookEndpointRepository)
	executionRepository := repositories.NewExecutionRepository(db)
	nodeExecutionRepository := repositories.NewNodeExecutionRepository(db)
	executionService := services.NewExecutionService(executionRepository, nodeExecutionRepository, workflowRepository)
	credentialRepository := repositories.NewCredentialRepository(db)
	credentialService := services.NewCredentialService(credentialRepository, encryptor)
	scheduleRepository := repositories.NewScheduleRepository(db)
	scheduleService := services.NewScheduleService(scheduleRepository)
	planRepository := repositories.NewPlanRepository(db)
	subscriptionRepository := repositories.NewSubscriptionRepository(db)
	usageRepository := repositories.NewUsageRepository(db)
	invoiceRepository := repositories.NewInvoiceRepository(db)
	billingService := wire.ProvideBillingService(planRepository, subscriptionRepository, usageRepository, invoiceRepository, workspaceRepository, workflowRepository, workspaceMemberRepository, credentialRepository)
	oAuthStateRepository := repositories.NewOAuthStateRepository(db)
	baseURL := wire.ProvideBaseURL(config)
	frontendURL := wire.ProvideFrontendURL(config)
	oAuthService := wire.ProvideOAuthService(oAuthStateRepository, credentialRepository, encryptor, config, baseURL, frontendURL)
	templateRepository := repositories.NewTemplateRepository(db)
	templateService := services.NewTemplateService(templateRepository, workflowRepository)
	webhookManager := wire.ProvideWebhookManager(webhookEndpointRepository, baseURL)
	waitingExecutionRepository := repositories.NewWaitingExecutionRepository(db)
	waitResumeManager := wire.ProvideWaitResumeManager(waitingExecutionRepository, baseURL)
	baseRepository := wire.ProvideAuditLogRepo(db)
	auditLogService := services.NewAuditLogService(baseRepository)
	repositoriesBaseRepository := wire.ProvideAlertRepo(db)
	baseRepository2 := wire.ProvideAlertLogRepo(db)
	alertService := services.NewAlertService(repositoriesBaseRepository, baseRepository2)
	baseRepository3 := wire.ProvideCommentRepo(db)
	workflowCommentService := services.NewWorkflowCommentService(baseRepository3)
	baseRepository4 := wire.ProvideExecShareRepo(db)
	executionShareService := services.NewExecutionShareService(baseRepository4)
	baseRepository5 := wire.ProvideEnvVarRepo(db)
	environmentVariableService := wire.ProvideEnvVarService(baseRepository5, encryptor)
	baseRepository6 := wire.ProvideWorkspaceAnalyticsRepo(db)
	baseRepository7 := wire.ProvideWorkflowAnalyticsRepo(db)
	analyticsService := wire.ProvideAnalyticsService(baseRepository6, baseRepository7, executionRepository)
	baseRepository8 := wire.ProvideWorkflowExportRepo(db)
	baseRepository9 := wire.ProvideWorkflowImportRepo(db)
	workflowExportService := wire.ProvideExportImportService(baseRepository8, baseRepository9, workflowRepository)
	executionReplayService := wire.ProvideExecutionReplayService(executionService, executionRepository)
	versionDiffService := wire.ProvideVersionDiffService(workflowRepository, workflowVersionRepository)
	apiKeyRepository := repositories.NewAPIKeyRepository(db)
	apiKeyService := services.NewAPIKeyService(apiKeyRepository)
	workflowVariableService := services.NewWorkflowVariableService(db)
	folderService := services.NewFolderService(db)
	workflowShareService := services.NewWorkflowShareService(db)
	marketplaceService := services.NewMarketplaceService(db)
	templateRatingService := services.NewTemplateRatingService(db)
	binaryDataService := wire.ProvideBinaryDataService(db)
	dashboardService := wire.ProvideDashboardService(db, workflowRepository, executionRepository, credentialRepository, scheduleRepository)
	apiServices := wire.ProvideServices(authService, userService, workspaceService, workflowService, executionService, credentialService, scheduleService, billingService, oAuthService, templateService, webhookManager, waitResumeManager, auditLogService, alertService, workflowCommentService, executionShareService, environmentVariableService, analyticsService, workflowExportService, executionReplayService, versionDiffService, apiKeyService, workflowVariableService, folderService, workflowShareService, marketplaceService, templateRatingService, binaryDataService, dashboardService)
	pinnedDataRepository := repositories.NewPinnedDataRepository(db)
	apiRepositories := wire.ProvideRepositories(pinnedDataRepository, waitingExecutionRepository, webhookEndpointRepository)
	app := provideApp(config, db, client, queueClient, jwtManager, manager, apiServices, apiRepositories)
	return app, nil
}

// wire.go:

// App holds all initialized dependencies
type App struct {
	Config       *config.Config
	DB           *gorm.DB
	Redis        *redis.Client
	Queue        *queue.Client
	JWTManager   *crypto.JWTManager
	OAuthManager *oauth.Manager
	Services     *api.Services
	Repos        *api.Repositories
}

// provideApp creates the App struct with all dependencies
func provideApp(
	cfg *config.Config,
	db *gorm.DB, redis2 *redis.Client, queue2 *queue.Client,
	jwt *crypto.JWTManager,
	oauthMgr *oauth.Manager, services2 *api.Services,
	repos *api.Repositories,
) *App {
	return &App{
		Config:       cfg,
		DB:           db,
		Redis:        redis2,
		Queue:        queue2,
		JWTManager:   jwt,
		OAuthManager: oauthMgr,
		Services:     services2,
		Repos:        repos,
	}
}
