// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"fmt"
	"github.com/google/wire"
	"github.com/linkflow-ai/linkflow/internal/adapters/messaging/asynq"
	"github.com/linkflow-ai/linkflow/internal/adapters/persistence/postgres"
	"github.com/linkflow-ai/linkflow/internal/adapters/persistence/postgres/repositories"
	"github.com/linkflow-ai/linkflow/internal/adapters/persistence/redis"
	"github.com/linkflow-ai/linkflow/internal/core/application/command/execution"
	"github.com/linkflow-ai/linkflow/internal/core/application/command/user"
	"github.com/linkflow-ai/linkflow/internal/core/application/command/workflow"
	"github.com/linkflow-ai/linkflow/internal/core/application/command/workspace"
	execution2 "github.com/linkflow-ai/linkflow/internal/core/application/query/execution"
	user2 "github.com/linkflow-ai/linkflow/internal/core/application/query/user"
	workflow2 "github.com/linkflow-ai/linkflow/internal/core/application/query/workflow"
	workspace2 "github.com/linkflow-ai/linkflow/internal/core/application/query/workspace"
	"github.com/linkflow-ai/linkflow/internal/core/domain/credential"
	execution3 "github.com/linkflow-ai/linkflow/internal/core/domain/execution"
	"github.com/linkflow-ai/linkflow/internal/core/domain/schedule"
	user3 "github.com/linkflow-ai/linkflow/internal/core/domain/user"
	"github.com/linkflow-ai/linkflow/internal/core/domain/webhook"
	workflow3 "github.com/linkflow-ai/linkflow/internal/core/domain/workflow"
	workspace3 "github.com/linkflow-ai/linkflow/internal/core/domain/workspace"
	"github.com/linkflow-ai/linkflow/internal/infrastructure/auth/jwt"
	"github.com/linkflow-ai/linkflow/internal/infrastructure/cache"
	"github.com/linkflow-ai/linkflow/internal/infrastructure/config"
	"github.com/linkflow-ai/linkflow/internal/infrastructure/crypto"
	"github.com/linkflow-ai/linkflow/internal/infrastructure/observability/logger"
	"github.com/linkflow-ai/linkflow/internal/shared/events"
	"gorm.io/gorm"
	"os"
)

// Injectors from wire.go:

// InitializeApp wires all dependencies
func InitializeApp() (*App, error) {
	config, err := provideConfig()
	if err != nil {
		return nil, err
	}
	logger := provideLogger(config)
	db, err := provideGormDB(config)
	if err != nil {
		return nil, err
	}
	client := providePostgresClient(db)
	redisClient, err := provideRedis(config)
	if err != nil {
		return nil, err
	}
	asynqClient, err := provideAsynqClient(config)
	if err != nil {
		return nil, err
	}
	cache := provideCache(redisClient)
	manager := provideJWTManager(config)
	v := provideHasher()
	userRepository := repositories.NewUserRepository(db)
	sessionRepository := repositories.NewSessionRepository(db)
	workspaceRepository := repositories.NewWorkspaceRepository(db)
	memberRepository := repositories.NewMemberRepository(db)
	workflowRepository := repositories.NewWorkflowRepository(db)
	versionRepository := repositories.NewVersionRepository(db)
	executionRepository := repositories.NewExecutionRepository(db)
	nodeExecutionRepository := repositories.NewNodeExecutionRepository(db)
	credentialRepository := repositories.NewCredentialRepository(db)
	scheduleRepository := repositories.NewScheduleRepository(db)
	webhookRepository := repositories.NewWebhookRepository(db)
	rbacRepository := repositories.NewRBACRepository(db)
	bus := provideEventBus()
	registerUserHandler := user.NewRegisterUserHandler(userRepository, manager, bus)
	loginUserHandler := user.NewLoginUserHandler(userRepository, sessionRepository, manager, bus)
	createWorkflowHandler := workflow.NewCreateWorkflowHandler(workflowRepository, versionRepository, bus)
	updateWorkflowHandler := workflow.NewUpdateWorkflowHandler(workflowRepository, versionRepository)
	activateWorkflowHandler := workflow.NewActivateWorkflowHandler(workflowRepository, nil, bus)
	createWorkspaceHandler := workspace.NewCreateWorkspaceHandler(workspaceRepository, memberRepository, rbacRepository, bus)
	taskQueue := provideTaskQueue(asynqClient)
	startExecutionHandler := execution.NewStartExecutionHandler(workflowRepository, executionRepository, bus, taskQueue)
	getUserHandler := user2.NewGetUserHandler(userRepository)
	getWorkflowHandler := workflow2.NewGetWorkflowHandler(workflowRepository)
	listWorkflowsHandler := workflow2.NewListWorkflowsHandler(workflowRepository)
	getVersionsHandler := workflow2.NewGetVersionsHandler(versionRepository)
	getWorkspaceHandler := workspace2.NewGetWorkspaceHandler(workspaceRepository)
	listWorkspacesHandler := workspace2.NewListWorkspacesHandler(memberRepository)
	listMembersHandler := workspace2.NewListMembersHandler(memberRepository)
	getExecutionHandler := execution2.NewGetExecutionHandler(executionRepository)
	listExecutionsHandler := execution2.NewListExecutionsHandler(executionRepository)
	app := provideApp(config, logger, client, redisClient, asynqClient, cache, manager, v, userRepository, sessionRepository, workspaceRepository, memberRepository, workflowRepository, versionRepository, executionRepository, nodeExecutionRepository, credentialRepository, scheduleRepository, webhookRepository, registerUserHandler, loginUserHandler, createWorkflowHandler, updateWorkflowHandler, activateWorkflowHandler, createWorkspaceHandler, startExecutionHandler, getUserHandler, getWorkflowHandler, listWorkflowsHandler, getVersionsHandler, getWorkspaceHandler, listWorkspacesHandler, listMembersHandler, getExecutionHandler, listExecutionsHandler)
	return app, nil
}

// wire.go:

// App holds all dependencies for the API server
type App struct {
	Config *config.Config
	Logger logger.Logger
	DB     *postgres.Client
	Redis  *redis.Client
	Queue  *asynq.Client
	Cache  cache.Cache
	JWT    *jwt.Manager
	Hasher *crypto.Hasher

	// Repositories
	UserRepo       user3.Repository
	SessionRepo    user3.SessionRepository
	WorkspaceRepo  workspace3.Repository
	MemberRepo     workspace3.MemberRepository
	WorkflowRepo   workflow3.Repository
	VersionRepo    workflow3.VersionRepository
	ExecutionRepo  execution3.Repository
	NodeExecRepo   execution3.NodeExecutionRepository
	CredentialRepo credential.Repository
	ScheduleRepo   schedule.Repository
	WebhookRepo    webhook.Repository

	// Command Handlers
	RegisterUserHandler     *user.RegisterUserHandler
	LoginUserHandler        *user.LoginUserHandler
	CreateWorkflowHandler   *workflow.CreateWorkflowHandler
	UpdateWorkflowHandler   *workflow.UpdateWorkflowHandler
	ActivateWorkflowHandler *workflow.ActivateWorkflowHandler
	CreateWorkspaceHandler  *workspace.CreateWorkspaceHandler
	StartExecutionHandler   *execution.StartExecutionHandler

	// Query Handlers
	GetUserHandler        *user2.GetUserHandler
	GetWorkflowHandler    *workflow2.GetWorkflowHandler
	ListWorkflowsHandler  *workflow2.ListWorkflowsHandler
	GetVersionsHandler    *workflow2.GetVersionsHandler
	GetWorkspaceHandler   *workspace2.GetWorkspaceHandler
	ListWorkspacesHandler *workspace2.ListWorkspacesHandler
	ListMembersHandler    *workspace2.ListMembersHandler
	GetExecutionHandler   *execution2.GetExecutionHandler
	ListExecutionsHandler *execution2.ListExecutionsHandler
}

// Infrastructure provider set
var infraSet = wire.NewSet(
	provideConfig,
	provideLogger,
	provideGormDB,
	providePostgresClient,
	provideRedis,
	provideAsynqClient,
	provideTaskQueue,
	provideCache,
	provideJWTManager,
	provideHasher,
	provideEventBus,
)

// Repository provider set
var repoSet = wire.NewSet(repositories.NewUserRepository, repositories.NewSessionRepository, repositories.NewWorkspaceRepository, repositories.NewMemberRepository, repositories.NewWorkflowRepository, repositories.NewVersionRepository, repositories.NewExecutionRepository, repositories.NewNodeExecutionRepository, repositories.NewCredentialRepository, repositories.NewScheduleRepository, repositories.NewWebhookRepository, wire.Bind(new(user3.Repository), new(*repositories.UserRepository)), wire.Bind(new(user3.SessionRepository), new(*repositories.SessionRepository)), wire.Bind(new(workspace3.Repository), new(*repositories.WorkspaceRepository)), wire.Bind(new(workspace3.MemberRepository), new(*repositories.MemberRepository)), wire.Bind(new(workflow3.Repository), new(*repositories.WorkflowRepository)), wire.Bind(new(workflow3.VersionRepository), new(*repositories.VersionRepository)), wire.Bind(new(execution3.Repository), new(*repositories.ExecutionRepository)), wire.Bind(new(execution3.NodeExecutionRepository), new(*repositories.NodeExecutionRepository)), wire.Bind(new(credential.Repository), new(*repositories.CredentialRepository)), wire.Bind(new(schedule.Repository), new(*repositories.ScheduleRepository)), wire.Bind(new(webhook.Repository), new(*repositories.WebhookRepository)))

// Command handler provider set
var commandSet = wire.NewSet(user.NewRegisterUserHandler, user.NewLoginUserHandler, workflow.NewCreateWorkflowHandler, workflow.NewUpdateWorkflowHandler, workflow.NewActivateWorkflowHandler, workflow.NewDeactivateWorkflowHandler, workspace.NewCreateWorkspaceHandler, execution.NewStartExecutionHandler)

// Query handler provider set
var querySet = wire.NewSet(user2.NewGetUserHandler, workflow2.NewGetWorkflowHandler, workflow2.NewListWorkflowsHandler, workflow2.NewGetVersionsHandler, workspace2.NewGetWorkspaceHandler, workspace2.NewListWorkspacesHandler, workspace2.NewListMembersHandler, execution2.NewGetExecutionHandler, execution2.NewListExecutionsHandler, execution2.NewGetNodeExecutionsHandler)

func provideConfig() (*config.Config, error) {
	configPath := os.Getenv("CONFIG_PATH")
	if configPath == "" {
		env := os.Getenv("APP_ENV")
		if env == "" {
			env = "local"
		}
		configPath = fmt.Sprintf("configs/config.%s.yaml", env)
	}
	return config.Load(configPath)
}

func provideLogger(cfg *config.Config) logger.Logger {
	if cfg.App.IsDevelopment() {
		return logger.NewDevelopment()
	}
	return logger.NewDefault()
}

func provideGormDB(cfg *config.Config) (*gorm.DB, error) {
	return postgres.NewClient(postgres.Config{
		Host:         cfg.Database.Host,
		Port:         cfg.Database.Port,
		User:         cfg.Database.User,
		Password:     cfg.Database.Password,
		Database:     cfg.Database.Name,
		SSLMode:      cfg.Database.SSLMode,
		MaxOpenConns: cfg.Database.MaxOpenConns,
		MaxIdleConns: cfg.Database.MaxIdleConns,
		MaxLifetime:  cfg.Database.MaxLifetime,
	})
}

func providePostgresClient(db *gorm.DB) *postgres.Client {
	return postgres.NewClientWrapper(db)
}

func provideRedis(cfg *config.Config) (*redis.Client, error) {
	return redis.NewClient(redis.Config{
		Host:     cfg.Redis.Host,
		Port:     cfg.Redis.Port,
		Password: cfg.Redis.Password,
		DB:       cfg.Redis.DB,
		PoolSize: cfg.Redis.PoolSize,
	})
}

func provideAsynqClient(cfg *config.Config) (*asynq.Client, error) {
	return asynq.NewClient(asynq.Config{
		RedisAddr:     cfg.Redis.GetAddress(),
		RedisPassword: cfg.Redis.Password,
		RedisDB:       cfg.Redis.DB,
	})
}

func provideTaskQueue(client *asynq.Client) execution.TaskQueue {
	return asynq.NewTaskQueueAdapter(client)
}

func provideCache(redis2 *redis.Client) cache.Cache {
	return cache.NewRedisCache(redis2.Redis(), "linkflow")
}

func provideJWTManager(cfg *config.Config) *jwt.Manager {
	return jwt.NewManager(jwt.Config{
		Secret:        cfg.JWT.Secret,
		AccessExpiry:  cfg.JWT.AccessExpiry,
		RefreshExpiry: cfg.JWT.RefreshExpiry,
		Issuer:        cfg.JWT.Issuer,
	})
}

func provideHasher() *crypto.Hasher {
	return crypto.NewHasher(10)
}

func provideEventBus() events.Bus {
	return events.NewInMemoryBus()
}

func provideApp(
	cfg *config.Config,
	log logger.Logger,
	db *postgres.Client, redis2 *redis.Client,
	queue *asynq.Client,
	cacheClient cache.Cache,
	jwtMgr *jwt.Manager,
	hasher *crypto.Hasher,
	userRepo user3.Repository,
	sessionRepo user3.SessionRepository,
	workspaceRepo workspace3.Repository,
	memberRepo workspace3.MemberRepository,
	workflowRepo workflow3.Repository,
	versionRepo workflow3.VersionRepository,
	executionRepo execution3.Repository,
	nodeExecRepo execution3.NodeExecutionRepository,
	credentialRepo credential.Repository,
	scheduleRepo schedule.Repository,
	webhookRepo webhook.Repository,
	registerUserHandler *user.RegisterUserHandler,
	loginUserHandler *user.LoginUserHandler,
	createWorkflowHandler *workflow.CreateWorkflowHandler,
	updateWorkflowHandler *workflow.UpdateWorkflowHandler,
	activateWorkflowHandler *workflow.ActivateWorkflowHandler,
	createWorkspaceHandler *workspace.CreateWorkspaceHandler,
	startExecutionHandler *execution.StartExecutionHandler,
	getUserHandler *user2.GetUserHandler,
	getWorkflowHandler *workflow2.GetWorkflowHandler,
	listWorkflowsHandler *workflow2.ListWorkflowsHandler,
	getVersionsHandler *workflow2.GetVersionsHandler,
	getWorkspaceHandler *workspace2.GetWorkspaceHandler,
	listWorkspacesHandler *workspace2.ListWorkspacesHandler,
	listMembersHandler *workspace2.ListMembersHandler,
	getExecutionHandler *execution2.GetExecutionHandler,
	listExecutionsHandler *execution2.ListExecutionsHandler,
) *App {
	return &App{
		Config:                  cfg,
		Logger:                  log,
		DB:                      db,
		Redis:                   redis2,
		Queue:                   queue,
		Cache:                   cacheClient,
		JWT:                     jwtMgr,
		Hasher:                  hasher,
		UserRepo:                userRepo,
		SessionRepo:             sessionRepo,
		WorkspaceRepo:           workspaceRepo,
		MemberRepo:              memberRepo,
		WorkflowRepo:            workflowRepo,
		VersionRepo:             versionRepo,
		ExecutionRepo:           executionRepo,
		NodeExecRepo:            nodeExecRepo,
		CredentialRepo:          credentialRepo,
		ScheduleRepo:            scheduleRepo,
		WebhookRepo:             webhookRepo,
		RegisterUserHandler:     registerUserHandler,
		LoginUserHandler:        loginUserHandler,
		CreateWorkflowHandler:   createWorkflowHandler,
		UpdateWorkflowHandler:   updateWorkflowHandler,
		ActivateWorkflowHandler: activateWorkflowHandler,
		CreateWorkspaceHandler:  createWorkspaceHandler,
		StartExecutionHandler:   startExecutionHandler,
		GetUserHandler:          getUserHandler,
		GetWorkflowHandler:      getWorkflowHandler,
		ListWorkflowsHandler:    listWorkflowsHandler,
		GetVersionsHandler:      getVersionsHandler,
		GetWorkspaceHandler:     getWorkspaceHandler,
		ListWorkspacesHandler:   listWorkspacesHandler,
		ListMembersHandler:      listMembersHandler,
		GetExecutionHandler:     getExecutionHandler,
		ListExecutionsHandler:   listExecutionsHandler,
	}
}
