apiVersion: v1
kind: ConfigMap
metadata:
  name: linkflow-config
  namespace: linkflow
data:
  APP_ENV: "production"
  APP_DEBUG: "false"
  DB_PORT: "5432"
  DB_SSLMODE: "require"
  REDIS_PORT: "6379"
